// Selected peer-reviewed work. `featured: true` promotes an entry to the top of
// the publications page and onto the home page. Every other entry needs a
// `category` key matching one in pubCategories.js; that decides which
// dropdown it lands in. Citation counts are from Google
// Scholar as of the date in pubStats.js; they are optional and can be dropped.
module.exports = [
  {
    featured: true,
    authors: "Khoury, C.K., Carver, D., Greene, S.L., Williams, K.A., Achicanoy, H.A., Schori, M., León, B., Wiersema, J.H., & Frances, A.",
    title: "Crop wild relatives of the United States require urgent conservation action",
    venue: "Proceedings of the National Academy of Sciences 117(52), 33351–33357",
    year: 2020,
    doi: "10.1073/pnas.2007029117",
    citations: 108,
    note: "The national baseline assessment of US crop wild relatives — 600 taxa modeled, threat-assessed, and gap-analyzed.",
  },
  {
    featured: true,
    authors: "Carver, D., Sosa, C.C., Khoury, C.K., Achicanoy, H.A., Diaz, M.V., Sotelo, S., Castañeda-Álvarez, N.P., & Ramírez-Villegas, J.",
    title: "GapAnalysis: an R package to calculate conservation indicators using spatial information",
    venue: "Ecography 44(7), 1000–1009",
    year: 2021,
    doi: "10.1111/ecog.05430",
    citations: 24,
    note: "The open-source implementation of the gap analysis method, and the foundation the GAMMa tool builds on.",
  },
  {
    featured: true,
    authors: "Carver, D., Khoury, C.K., Frances, A., McCarry, N., Diaz-Garcia, L., Galarneau, E., Gora, S., Haidet, M., Heinitz, C., Knapp, W., Meyer, A., Miller, A., Mims, R., Sapkota, S., Spurrier, C., & Wen, J.",
    title: "Conservation gap analysis for wild grapevines (Vitis L.) of the Americas",
    venue: "Plants, People, Planet",
    year: 2026,
    note: "The most recent application of the workflow, extending the national assessment to a new genus.",
  },
  {
    featured: true,
    authors: "Morrison, R.R., Simonson, K., McManamay, R.A., & Carver, D.",
    title: "Degradation of floodplain integrity within the contiguous United States",
    venue: "Communications Earth & Environment 4(1), 215",
    year: 2023,
    citations: 42,
    note: "Continental-scale spatial assessment outside the crop wild relatives domain.",
  },

  {
    category: "cwr",
    authors: "Khoury, C.K., Carver, D., Barchenger, D.W., Barboza, G.E., van Zonneveld, M., Jarret, R., Bohs, L., Kantar, M.B., Uchanski, M., Mercer, K., Nabhan, G.P., Bosland, P.W., & Greene, S.L.",
    title: "Modelled distributions and conservation status of the wild relatives of chile peppers (Capsicum L.)",
    venue: "Diversity and Distributions 26(2), 209–225",
    year: 2020,
    doi: "10.1111/ddi.13008",
    citations: 83,
  },
  {
    category: "cwr",
    authors: "Vining, K.J., Hummer, K.E., Bassil, N.V., Lange, B.M., Khoury, C.K., & Carver, D.",
    title: "Crop wild relatives as germplasm resource for cultivar improvement in mint (Mentha L.)",
    venue: "Frontiers in Plant Science 11, 1217",
    year: 2020,
    doi: "10.3389/fpls.2020.01217",
    citations: 65,
  },
  {
    category: "cwr",
    authors: "Khoury, C.K., Carver, D., Kates, H.R., Achicanoy, H.A., van Zonneveld, M., Thomas, E., Heinitz, C., Jarret, R., Labate, J.A., Reitsma, K., Nabhan, G.P., & Greene, S.L.",
    title: "Distributions, conservation status, and abiotic stress tolerance potential of wild cucurbits (Cucurbita L.)",
    venue: "Plants, People, Planet 2(3), 269–283",
    year: 2020,
    doi: "10.1002/ppp3.10085",
    citations: 57,
  },
  {
    category: "cwr",
    authors: "Lebeda, A., Křístková, E., Kitner, M., Majeský, L., Doležalová, I., Khoury, C.K., Carver, D., Achicanoy, H.A., Sosa, C.C., Widrlechner, M., & Hu, J.",
    title: "Research gaps and challenges in the conservation and exploitation of North American wild lettuce (Lactuca L.) germplasm",
    venue: "Crop Science 59(6), 2337–2356",
    year: 2019,
    doi: "10.2135/cropsci2019.05.0350",
    citations: 30,
  },
  {
    category: "cwr",
    authors: "Mezghani, N., Khoury, C.K., Carver, D., Achicanoy, H.A., Simon, P., Flores, F.M., & Spooner, D.",
    title: "Distributions and conservation status of carrot wild relatives in Tunisia: a case study in the western Mediterranean basin",
    venue: "Crop Science 59(6), 2317–2328",
    year: 2019,
    doi: "10.2135/cropsci2019.05.0333",
    citations: 29,
  },
  {
    category: "genetic-resources",
    authors: "Volk, G.M., Carver, D., Irish, B.M., Marek, L., Frances, A., Greene, S., Khoury, C.K., Bamberg, J., Bethke, P.C., Bisognin, D., & Bradeen, J.M.",
    title: "Safeguarding plant genetic resources in the United States during global climate change",
    venue: "Crop Science 63(4)",
    year: 2023,
    citations: 28,
  },
  {
    category: "cwr",
    authors: "Myrans, H., Diaz, M.V., Khoury, C.K., Carver, D., Henry, R.J., & Gleadow, R.",
    title: "Modelled distributions and conservation priorities of wild sorghums (Sorghum Moench)",
    venue: "Diversity and Distributions 26(12), 1727–1740",
    year: 2020,
    doi: "10.1111/ddi.13166",
    citations: 24,
  },
  {
    category: "remote-sensing",
    authors: "O'Shea, K., LaRoe, J., Vorster, A., Young, N., Evangelista, P., Mayer, T., Carver, D., Simonson, E., Martin, V., Radomski, P., Knopik, J., Kern, A., & Khoury, C.K.",
    title: "Improved remote sensing methods to detect northern wild rice (Zizania palustris L.)",
    venue: "Remote Sensing 12(18), 3023",
    year: 2020,
    doi: "10.3390/rs12183023",
    citations: 15,
  },
  {
    category: "remote-sensing",
    authors: "Engelstad, P., Carver, D., & Young, N.E.",
    title: "Creating presence and absence points, and Working with GPS and weather data",
    venue: "Cloud-Based Remote Sensing with Google Earth Engine (book chapters)",
    year: 2023,
  },
  {
    category: "genetic-resources",
    authors: "Johnson, R.C., Love, S.L., Carver, D., & Irish, B.M.",
    title: "Using climate-driven adaptive evolution to guide seed sourcing for restoration in a diverse North American herb-shrub species",
    venue: "Restoration Ecology 31(4), e13856",
    year: 2023,
    citations: 7,
  },
  {
    category: "genetic-resources",
    authors: "Greene, S.L., Carver, D., Khoury, C.K., Irish, B., Olwell, P., & Leah, P.",
    title: "Seeds of Success: collateral benefits to agricultural crop improvement, research and education",
    venue: "Crop Science 59(6), 2429–2442",
    year: 2019,
    doi: "10.2135/cropsci2019.06.0372",
  },
  {
    category: "cwr",
    authors: "Lebeda, A., Křístková, E., Khoury, C.K., Carver, D., & Sosa, C.C.",
    title: "Distribution and ecology of wild lettuces Lactuca serriola L. and Lactuca virosa L. in central Chile",
    venue: "Hacquetia 21(1), 173–186",
    year: 2022,
    doi: "10.2478/hacq-2021-0019",
    citations: 5,
  },
  {
    category: "remote-sensing",
    authors: "Moreno-Sanchez, R., Carver, D.P., Torres-Rojo, J.M., & Anthamatten, P.",
    title: "Assessment of the classification accuracy of the Globeland30 forest class for the temperate and tropical forests of Mexico",
    venue: "Applied Geomatics 13(2), 147–163",
    year: 2021,
    doi: "10.1007/s12518-020-00328-1",
    citations: 5,
  },
  {
    category: "landscape",
    authors: "Woodward, B., Evangelista, P., Young, N., Vorster, A., West, A., Carroll, S., Girma, R., Hatcher, E., Anderson, R., Vahsen, M., Vashisht, A., Mayer, T., Carver, D., & Jarnevich, C.",
    title: "CO-RIP: a riparian vegetation and corridor extent dataset for Colorado River Basin streams and rivers",
    venue: "ISPRS International Journal of Geo-Information 7(10), 397",
    year: 2018,
    doi: "10.3390/ijgi7100397",
  },
  {
    category: "landscape",
    authors: "Carver, D.P., & Beeton, J.M.",
    title: "Holocene landscape evolution and geoarchaeology of low-order streams in the Rio Grande basin, San Juan Mountains, Colorado, USA",
    venue: "Quaternary Research 82, 331–341",
    year: 2014,
    doi: "10.1016/j.yqres.2014.05.006",
  },
];
